#!/usr/bin/env python3
"""
Generate the preview pages.

Each page's own content (hero + main) lives in src/<slug>.html, whose first line is an HTML
comment carrying its <title> and meta description. The chrome around it (the unofficial
ribbon, the club's masthead, the strip linking every page in this preview, the footer) is
the same on every page, so it lives here. Run `python3 build.py` and commit the HTML it
writes; GitHub Pages serves plain static files.
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = "https://www.mvnadadores.org"
LOGO = ("https://images.squarespace-cdn.com/content/v1/6051c74da87b5d5b5c827b28/"
        "bf1a8742-1185-4223-9169-90adb0677a7d/nadadores+logo_foundation.png?format=300w")

# Every page in this preview: (file, label, the club page it replicates)
PAGES = [
    ("index.html",          "Home",               "/"),
    ("pool-schedule.html",  "Marguerite Pools",   "/team-training-in-mission-viejo"),
    ("swim-team.html",      "Swim Team",          "/programs/swim-team"),
    ("dive-team.html",      "Dive Team",          "/programs/dive-team"),
    ("swim-school.html",    "Swim School",        "/programs/swim-school"),
    ("masters-swim.html",   "Masters Swim",       "/programs/masters-swim"),
    ("events.html",         "Events",             "/events"),
]
ORIGIN = {f: SITE + path for f, _, path in PAGES}

EXT = 'target="_blank" rel="noopener noreferrer"'


def ext(path, label):
    return f'<a href="{SITE}{path}" {EXT}>{label}</a>'


def shell(slug, title, description, body):
    origin = ORIGIN[slug]
    shown = origin.replace("https://www.", "")
    on = ' class="on" aria-current="page"'
    strip = "\n".join(
        f'    <a href="{f}"{on if f == slug else ""}>{label}</a>'
        for f, label, _ in PAGES)
    is_prog = slug in ("swim-team.html", "dive-team.html", "swim-school.html", "masters-swim.html")
    here_prog = '<span class="here">Programs</span>' if is_prog else '<a href="swim-team.html">Programs</a>'
    here_events = '<span class="here">Events</span>' if slug == "events.html" else '<a href="events.html">Events</a>'
    return f"""<!doctype html>
<!--
  UNOFFICIAL PREVIEW. Not a Mission Viejo Nadadores website.
  A replica of {origin}
  Generated by build.py from src/{slug} &mdash; edit those, not this file.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap">
<link rel="stylesheet" href="site.css">
</head>
<body>

<div class="preview-note">
  <b>Unofficial preview.</b> Not a Mission Viejo Nadadores page &mdash; a mock-up of
  <a href="{origin}" {EXT}>{shown}</a>
  with its posted times replaced by a live calendar. Built by
  <a href="https://www.poolrelay.com" {EXT}>Pool Relay</a>.
</div>

<header class="site">
  <div class="bar">
    <a href="index.html"><img src="{LOGO}" alt="Mission Viejo Nadadores"></a>
    <nav class="site">
      {ext("/history/how-we-started", "History")}
      {here_prog}
      <a href="pool-schedule.html">Team Training</a>
      {ext("/team/swim-coaches", "Team")}
      {ext("/our-alumni", "Alumni")}
      {here_events}
      <a class="cta" href="{SITE}/donate" {EXT}>Donate</a>
    </nav>
  </div>
  <nav class="strip" aria-label="Pages in this preview">
{strip}
  </nav>
</header>

{body.strip()}

<footer class="site">
  <div class="in">
    <div>
      <b>Mission Viejo Nadadores</b>
      A tradition of excellence since 1968. Developing champions in the water and leaders in life.<br><br>
      Marguerite Aquatics Complex<br>
      27474 Casta Del Sol, Unit 2, Mission Viejo, CA 92692<br>
      Swim office: <a href="mailto:swimoffice@mvnadadores.org">swimoffice@mvnadadores.org</a> &middot; (949) 380-2552<br>
      Dive office: <a href="mailto:diveoffice@mvnadadores.org">diveoffice@mvnadadores.org</a> &middot; (949) 290-8669
    </div>
    <div>
      <b>Programs</b>
      <ul>
        <li><a href="swim-team.html">Swim Team</a></li>
        <li><a href="dive-team.html">Dive Team</a></li>
        <li><a href="swim-school.html">Swim School</a></li>
        <li><a href="masters-swim.html">Masters Swim</a></li>
      </ul>
    </div>
    <div>
      <b>More</b>
      <ul>
        <li><a href="pool-schedule.html">Marguerite Pools</a></li>
        <li><a href="events.html">Upcoming Events</a></li>
        <li>{ext("/donate", "Donate")}</li>
        <li>{ext("/alumni/our-community/contact-us", "Contact Us")}</li>
      </ul>
    </div>
  </div>
  <p class="fine">This page is an unofficial preview built to demonstrate an embedded
    <a href="https://www.poolrelay.com" {EXT}>Pool Relay</a>
    calendar. It is not operated by or affiliated with the Mission Viejo Nadadores or the City of
    Mission Viejo. For official schedules see
    <a href="{SITE}/" {EXT}>mvnadadores.org</a>, <a href="https://mvndiving.com/" {EXT}>mvndiving.com</a>
    and <a href="https://www.mvnswimschool.org/" {EXT}>mvnswimschool.org</a>.</p>
</footer>

</body>
</html>
"""


def main():
    for slug, _, _ in PAGES:
        src = open(os.path.join(HERE, "src", slug), encoding="utf-8").read()
        m = re.match(r"\s*<!--\s*title:\s*(.*?)\n\s*description:\s*(.*?)\s*-->\s*", src, re.S)
        if not m:
            raise SystemExit(f"src/{slug}: first line must be the title/description comment")
        html = shell(slug, m.group(1).strip(), m.group(2).strip(), src[m.end():])
        open(os.path.join(HERE, slug), "w", encoding="utf-8").write(html)
        print("wrote", slug)


if __name__ == "__main__":
    main()
